const APIS = {
  SIGNUP: "/auth/signup/",
  LOGIN: "/auth/login/",
  FORGOTPASSWORD: "/auth/forgotPassword/",
  RESETPASSWORD: "/auth/resetPassword/",
  CATEGORYLIST: "/job/jobCategory/",
  MYCATEGORYLIST: "/job/myJobCategory/",
  ADDCATEGORY: "/job/createJobCategory/",
  SINGLECATEGORY: "/job/singleCategory/",
  UPDATECATEGORY: "/job/updateJobCategory/",
  DELETECATEGORY: "/job/deleteJobCategory/",
  COMPANYLIST: "/job/getCompany/",
  MYCOMPANY: "/job/myCompany/",
  ADDCOMPANY: "/job/createCompany/",
  SINGLECOMPANY: "/job/singleCompany/",
  UPDATECOMPANY: "/job/updateCompany/",
  DELETECOMPANY: "/job/deleteCompany/",
  ADDJOBS: "/job/createJob/",
  JOBLISTS: "/job/getAllJobs/",
  MYJOBS: "/job/myJobs/",
  DELETEJOBS: "/job/deleteJob/",
  SINGLEJOB: "/job/singleJob/",
  UPDATEJOB: "/job/updateJob/",
  SINGLEJOBDETAIL: "/job/singleJobDetail/",
  APPLYJOB: "/job/appliedJob/",
  VIEWJOBAPPLICANT: "/job/getJobApplicant/",
  DASHBOARDJOBAPPLICANT: "/job/dashBoardApplicantList/",
  UPDATEAPPLICANTSTATUS: "/job/updateApplicantStatus/",
  USERPROFILE: "/user/profile",
  UPDATEUSERPROFILE: "/user/updateProfile",
  UPDATEUSERPASSWORD: "/user/updatePassword",
};

export default APIS;
